sonar.organization=${env.SONAR_ORG}
sonar.projectKey=${env.SONAR_PROJECT}
sonar.projectName=cswebapi1
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=**/*.test.cs
sonar.exclusions=**/bin/**,**/obj/**,**/*.md,**/*.json,**/*.editorconfig,**/*.http,**/*.yml,**/*.yaml,**/*.xml,**/*.config,**/*.properties